### ISSUE TITLE
wavread.h  - Exception thrown: write access violation.

### ISSUE THREAD

**Issue by quakig** [TaleTN/WDL#1]
Hi

Am trying to use your wavread.h implementation to read a .wav file.

My code is a as follows:

```
  WaveReader* mAudioFile;
  double* pAudioBuffer;
  const char* fileName = "resources/samples/a4.wav";
  mAudioFile = new WaveReader(fileName);
  int64_t size = mAudioFile->GetSize();
  mAudioFile->ReadDoubles(pAudioBuffer, size);

```
As I step through the code in debugger, I get the following error message:

```
Exception thrown: write access violation.
**samples** was 0xCDCDCDCD. occurred
```

at line number 274 of wavread.h

`*samples++ = WDL_bswapf_if_be(a);`

I can see this line tries to swap endianness if big endian. But the error message is too cryptic for my current understanding.

![1](https://user-images.githubusercontent.com/2546691/34643516-5ed512be-f34b-11e7-8d4b-6e0500f6c383.png)

Any suggestions would be appreciated.

**Comment by TaleTN** [comment]
You need to allocate pAudioBuffer before calling ReadDoubles() i.e.:

```
WaveReader* mAudioFile;
double* pAudioBuffer;
const char* fileName = "resources/samples/a4.wav";
mAudioFile = new WaveReader(fileName);
int64_t size = mAudioFile->GetSize();
pAudioBuffer = new double[size]; // <--- Allocate buffer
mAudioFile->ReadDoubles(pAudioBuffer, size);
```

Note that GetSize() returns an unsigned int, not int64_t (so very large WAV files are not supported). And don't forget to delete mAudioFile and pAudioBuffer again!

**Comment by quakig** [comment]
thanks a lot. That solved the issue.
